### ISSUE TITLE
[Fabric] 1.19.2 - Server kick after opening Reforged Anvil GUI

### ISSUE THREAD

**Issue by pewblaze** [Globox1997/tiered#18]
Hi im crashing/loosing connection to the server when im trying to reforge my gear in the anvil.

Server log;
https://gist.github.com/pewblaze/f308f19b4444fed5ad80c96fa3c12306

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/tiered/commit/953f5baaca152afd390cd2a327944a8dd65a3217](https://github.com/Globox1997/tiered/commit/953f5baaca152afd390cd2a327944a8dd65a3217)

**Comment by pewblaze** [comment]
Thanks unfortunately its not fixed for me yet :/

I get another error now i guess? 
```
[12:23:27] [Netty Epoll Play IO Thread #2/ERROR]: Encountered exception while handling in channel with name "tiered:set_screen"
java.util.ConcurrentModificationException: null
```

Server log: 
https://gist.github.com/pewblaze/777f67efe85ab6182b9c8b6b2b6b1e3c

Client log:
https://gist.github.com/pewblaze/245d271bbdd93bf4dc03db72009edc8c

**Comment by Globox1997** [comment]
Pure pain xD

**Comment by pewblaze** [comment]
Sorry D: You know why it crashes? xD

**Comment by Globox1997** [comment]
Actually not sure, can't find something in the log

**Comment by staviq** [comment]
I'm getting this when trying to open reforging gui:

`[20:20:02] [Server thread/ERROR]: Error executing task on Server
java.lang.ClassCastException: class net.minecraft.class_1723 cannot be cast to class draylar.tiered.reforge.ReforgeScreenHandler (net.minecraft.class_1723 and draylar.tiered.reforge.ReforgeScreenHandler are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @7f560810)
        at draylar.tiered.network.TieredServerPacket.lambda$init$3(TieredServerPacket.java:52) ~[tiered-1.1.3.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by Baromeus** [comment]
I have the same Error as staviq on Fabric for MC 1.18.2
In Game the GUI just closes if you click the Reforge Tab

additional Info: using AQM2

**Comment by Globox1997** [comment]
fixed for 1.19.2 with [https://github.com/Globox1997/tiered/commit/56bda05e2b0122d9a4e8e75e4cdc55c185deb53d](https://github.com/Globox1997/tiered/commit/56bda05e2b0122d9a4e8e75e4cdc55c185deb53d)
