### ISSUE TITLE
Any item that is crafted and isn't "Tierable" can become duplicated by giving materials back

### ISSUE THREAD

**Issue by LunexLunertic** [Globox1997/tiered#23]
So, any sort of item that isn't a weapon, tool, or armor when used in a crafting table (even in item inventory) can become duplicated, I tested it out here in this video and when I removed tiered it would act normally. I do not know if it is due to some other mod as I haven't tested it with only this mod but nonetheless it's really easy to duplicate anything since you get your materials back unless it is turned into a weapon, tool, or armor.

On that note shift clicking on items that aren't a weapon, tool, or armor will not give multiple of that item since it's not "tierable" so its a strange sort of bug that gives you back your materials, you can't shift click to make multiple of items unless it is the one of the three categories noted above.

I have a video to show the bug in action. I forgot to show it also happening in inventory screen but you get the idea.

https://youtu.be/28OYM0Q_z0M

**Comment by LunexLunertic** [comment]
Almost forgot to post the log but yes it is indeed showing here that it is attempting to apply the "Tier" to the items that I craft.
[latest.log](https://github.com/Globox1997/tiered/files/9934598/latest.log)

**Comment by Globox1997** [comment]
Thanks for reporting, I think it is fixed with [https://github.com/Globox1997/tiered/commit/1d9abc569a9812132a4b24a1be36ddd53b044d87](https://github.com/Globox1997/tiered/commit/1d9abc569a9812132a4b24a1be36ddd53b044d87)

**Comment by Baddy-Plays** [comment]
I am on 1.1.4 version of Tiered on 1.19.2 and the duplication bug mentioned here is still happening. 
Is this implemented yet?

**Comment by Globox1997** [comment]
Will be in 1.1.5
